arch: 
  - ppc64le
  - amd64
language: python
python:
  - "3.6"
install:
  - sleep 9m
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-ppc64le.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment

script:
  - conda install -y git
  - conda config --prepend channels https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
  - export IBM_POWERAI_LICENSE_ACCEPT=yes
  - conda install --yes --quiet conda-forge-ci-setup=2 conda-build=3.19.2 -c conda-forge
